// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHipBIhm5n253f3f7F61J7nqjbIOc3Tk0',
    appId: '1:1089931993620:web:60658c870b2b86d60ebd01',
    messagingSenderId: '1089931993620',
    projectId: 'garden-guru-469f9',
    authDomain: 'garden-guru-469f9.firebaseapp.com',
    storageBucket: 'garden-guru-469f9.appspot.com',
    measurementId: 'G-C0FBFQRGZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkm3YubMjwNf61L5aoS9d1UnpVc20LoVo',
    appId: '1:1089931993620:android:8c36c47a41d90ab30ebd01',
    messagingSenderId: '1089931993620',
    projectId: 'garden-guru-469f9',
    storageBucket: 'garden-guru-469f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixXSEYKBuy3AUYY8s1ZHZoT5m7Rfvgi4',
    appId: '1:1089931993620:ios:4e38338d2c9efaa00ebd01',
    messagingSenderId: '1089931993620',
    projectId: 'garden-guru-469f9',
    storageBucket: 'garden-guru-469f9.appspot.com',
    iosBundleId: 'com.example.gardengru',
  );
}
